import type { Metadata } from "next";
import { Manrope, Quicksand, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/elements/header";
import QueryProvider from "@/providers/query-provider";
import Footer from "@/components/elements/footer";
import LenisProvider from "@/providers/lenis-provider";

const manrope = Manrope({ subsets: ["latin"] });
const quicksand = Quicksand({ subsets: ["latin"] });
// const poppins = Poppins();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={manrope.className}
      >
        <QueryProvider>
          <LenisProvider>
          <Header />
          {children}
          <Footer />
          </LenisProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
